# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_library
cc_library(
    name = "hellogreet",
    srcs = ["hellogreet.cc"],
    hdrs = ["hellogreet.h"],
    visibility = ["//main:__pkg__"],
)